<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="Mock_FilesystemEntry" Id="{acbcab05-a2a1-47d3-8447-d5538d9585da}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'hide'}
FUNCTION_BLOCK PUBLIC Mock_FilesystemEntry EXTENDS FileSystemEntry
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Mock_FilesystemEntry">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>